name: agrihub_dashboard
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  camera: ^0.11.1
  web_socket_channel: ^3.0.2
  image_picker: ^1.1.2
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1
  video_player: ^2.9.3
  video_player_web_hls: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/No Camera.png
