name: agrihub_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  camera: ^0.10.0+1
  web_socket_channel: ^2.2.0
  image_picker: ^1.1.2
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
