name: agrihub_dashboard
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  camera: ^0.11.1
  web_socket_channel: ^3.0.2
  image_picker: ^1.1.2
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1
  video_player: ^2.9.3
  video_player_web_hls: ^1.3.0
  image: ^4.5.3
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  provider: ^6.1.4
  dropdown_search: ^6.0.2
  flutter_svg: ^2.0.17
  syncfusion_flutter_charts: ^29.1.38
  cached_network_image: ^3.4.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/No Camera.png
    - assets/early_growth_icon.png
    - assets/leafy_growth_icon.png
    - assets/head_formation_icon.png
    - assets/harvest_stage_icon.png
    - assets/agrivision_icon.png
    - assets/camera.png
    - assets/plant.png
    - assets/apu_logo.png
    - assets/apcore_logo.png
